application: teamzones-1283
version: v0-1-2
runtime: go
api_version: go1
instance_class: F1
automatic_scaling:
  min_idle_instances: 2

default_expiration: 14d

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: /sign-up/free/
  login: admin
  script: _go_app

- url: /.*
  script: _go_app
  secure: always
