application: teamzones-1283
version: v0-0-1
runtime: go
api_version: go1

default_expiration: 14d

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: /.*
  script: _go_app
